allowBuilds:
  '@parcel/watcher': false
  unrs-resolver: false

# https://pnpm.io/settings#enginestrict
engineStrict: true

# https://pnpm.io/settings#ignoredbuiltdependencies
ignoredBuiltDependencies:

# https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 4320

# https://pnpm.io/settings#minimumreleaseageexclude
minimumReleaseAgeExclude:

# https://pnpm.io/settings#nodelinker
nodeLinker: hoisted

# https://pnpm.io/settings#supportedarchitectures
supportedArchitectures:
  os: [ darwin, linux ]

# https://pnpm.io/settings#trustpolicy
trustPolicy: no-downgrade

# https://pnpm.io/settings#trustpolicyexclude
trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0

# https://pnpm.io/settings#overrides
overrides:
  body-parser: 2.3.0
  brace-expansion@^1: 1.1.18
  brace-expansion@^2: 2.1.4
  fast-uri: 3.1.5
  js-yaml: 3.15.1
