# https://pnpm.io/settings#enginestrict
engineStrict: true

# https://pnpm.io/settings#ignoredbuiltdependencies
ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - unrs-resolver

# https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 4320

# https://pnpm.io/settings#minimumreleaseageexclude
minimumReleaseAgeExclude:

# https://pnpm.io/settings#nodelinker
nodeLinker: hoisted

# https://pnpm.io/settings#overrides
overrides:
  fast-uri: "^3.1.1"
  qs: "^6.15.2"

# https://pnpm.io/settings#supportedarchitectures
supportedArchitectures:
  os: [darwin, linux]

# https://pnpm.io/settings#trustpolicy
trustPolicy: no-downgrade

# https://pnpm.io/settings#trustpolicyexclude
trustPolicyExclude:
  - semver@6.3.1
