engineStrict: true

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - unrs-resolver

minimumReleaseAge: 4320

nodeLinker: hoisted

overrides:
  mailparser>nodemailer: ^7.0.11

supportedArchitectures:
  os: [darwin, linux]

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0
