engineStrict: true

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - unrs-resolver

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - aws-cdk@2.1106.1

nodeLinker: hoisted

overrides:
  ajv: ^8.18.0
  fast-xml-parser: ^5.3.6
  minmatch: ^10.2.1
  # mailparser>nodemailer: ^7.0.11

supportedArchitectures:
  os: [darwin, linux]

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0
