name: Test hiding secrets

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bash-example:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          echo "::add-mask::${{secrets.AWS_ACCOUNT_ID}}"
          echo "::add-mask::${{secrets.AWS_DEFAULT_REGION}}"
      - name: bash-version
        run: |
          echo "::add-mask::$MY_NAME"
          echo "$MY_NAME"
          echo "dupadupa"
          echo "eu-west-1"
          echo "CI: ${{env.CI}}"
